cmake_minimum_required(VERSION 4.2)
set(CMAKE_CXX_MODULE_STD ON)
set(CMAKE_EXPERIMENTAL_CXX_IMPORT_STD "451f2fe2-a8a2-47c3-bc32-94786d8fc91b")
set(CMAKE_CXX_STANDARD 23)                                                  
set(CMAKE_CXX_STANDARD_REQUIRED ON)                                         
project("oop" LANGUAGES CXX)
add_subdirectory("pract")
add_subdirectory("labs")