cmake_minimum_required(VERSION 4.2)                                       
set(CMAKE_CXX_MODULE_STD ON)                                                
set(CMAKE_EXPERIMENTAL_CXX_IMPORT_STD "451f2fe2-a8a2-47c3-bc32-94786d8fc91b")
project(lab2 CXX)                                                           
add_executable(Practice7)                                                     
target_compile_features(Practice7 PUBLIC cxx_std_23)                          
target_sources(Practice7 PRIVATE "main.cpp") 